### ISSUE TITLE
ValueError: Cannot infer num from shape(?,?) when using as_rotation_matrix with a dynamic type

### ISSUE THREAD

**Issue by kevinkit** [PhilJd/tf-quaternion#7]
I am trying to write a metrics using quaternions, the code looks like the follwoing:

```
def vectorMAEquat(y_true,y_pred):
        
    p1 = tf.constant([[1,0,0],[0,1,0],[0,0,1]],dtype=tf.float32)
    p2 = tf.constant([[1,0,0],[0,1,0],[0,0,1]],dtype=tf.float32)
  
    q1 = tfq.Quaternion(y_true)
    q2 = tfq.Quaternion(y_pred)
    
    rot1 = tf.matmul(q1.as_rotation_matrix(),p1)
    rot2 = tf.matmul(q2.as_rotation_matrix(),p2)
    
    return K.mean(K.abs(rot1 - rot2))
```

However, this gives me the error:` ValueError: Cannot infer num from shape(?,?)` which comes form the function

`w,x,y,z = tf.unstack(self.normalized().value(),axis=-1)` from the file `tfquaternion.py` , in line `364 `in the function `as_rotation_matrix`.

A little bit of googling brought me here: https://stackoverflow.com/questions/45404056/tf-unstack-with-dynamic-shape  

So, maybe this would be a nice feature, if as_rotation_matrix could work with dynamic_partition, but I am not fluent enough in tensorflow to achieve this, so any pointers would be really appreciated.

Thank you

**Comment by PhilJd** [comment]
Hi,
I've pushed a commit that adds num=4 to unstack, this should hopefully resolve this issue. Can you check if this fixes the error? Then I'd update the pip package.

Thanks :)

**Comment by kevinkit** [comment]
Thanks for the quick fix, is it already on PyPi or do I need to install it from the github page?

**Comment by PhilJd** [comment]
I just pushed it to PyPi :)

**Comment by kevinkit** [comment]
I tried it, however the error still occurs. I am using it as a metrics for model.fit_generator(...) , the `"num=4" `can be seen in the error message.

**Comment by PhilJd** [comment]
What is your dynamic shape? Is it  4 in the correct dimension? Also, is the error message the same, i.e., `ValueError: Cannot infer num from shape(?,?)` ?

**Comment by kevinkit** [comment]
Yes I think so, cause I am using the following loss function:


```
def quatloss(y_true,y_pred):
   q1 = tfq.Quaternion(y_true)
   q2 = tfq.Quaternion(y_pred)
   return K.mean(K.abs(q1-q2))
```

Which works, so my Dimension is: `(batch_size,4)`, my used batch_size is 8

**Comment by PhilJd** [comment]
Which tensorflow version are you using?
I'm using
```
tf.__version__
'1.13.0-dev20190104
```
For me the following code works well:
```
import tensorflow as tf
import tfquaternion as tfq
pl = tf.placeholder(tf.float32, (None, None))
q1 = tfq.Quaternion(pl)
matrix = q1.as_rotation_matrix()
with tf.Session() as sess:
  sess.run(matrix, feed_dict={pl: [[1,2,3,4]]})
```

**Comment by kevinkit** [comment]
I am on tf.__version__ 1.10.1, I wll test the sniuppet as soon as my GPU is free again ;)

**Comment by kevinkit** [comment]
Thank you the acutal problem is gone now.
Sadly a new error occurs, which has nothing to do with this project, but is mir likely to be a tensorflow issue:
```
ValueError: Shape must be rank 2 but is rank 3 for 'metrics_4/vectorMAEquat/MatMul' (op: 
MatMul') with input shapes: [?,3,3], [3.3]
```
I think it has something to do with the `p1 `and `p2 `constant

**Comment by PhilJd** [comment]
Yep, `p1` and `p2` should probably have shape `[1,3,3]`.

**Comment by kevinkit** [comment]
had to use the batch size in the constant:
`
p1 = tf.constant(batch_size*[[[1,00],[0,1,0],[0,0,1]]])`

fixed it. Thank you really much.
